# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EMPlacePicker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EMPlacePicker
  pod 'SnapKit', '~> 4.0.0'
  pod 'FloatingPanel'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  #pod 'RxCocoa',    '~> 4.0'
end
